name: ExtendedBucketsPlugin
version: 0.1.0
main: com.backslide999.extendedbuckets.ExtendedBucketsPlugin
api-version: 1.13
author: Backslide999
description: Include buckets that can hold multiple charges

softdepend: [PlaceholderAPI]

commands:

  extendedbuckets:
    description: Main plugin command
    aliases: [eb, ebuckets]
    permission-message: §cYou do not have permission to use that command!
    usage: §9/ebuckets help

permissions:
